source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

project 'Espressos'

target :Espressos do
  pod 'TTTAttributedLabel', :path => '../'

  target :TTTAttributedLabelTests do
      inherit! :search_paths
      pod 'FBSnapshotTestCase/Core'
      pod 'Expecta'
      pod 'OCMock'
      pod 'KIF', '~> 3.9.0'
  end
end
